### ISSUE TITLE
Value of C4/5/7/8/9/10/11/12

### ISSUE THREAD

**Issue by KeLaiFu** [gerb-ster/Ronnberg-LFO#1]
I've made some PCBs from your layouts and just noticed there's no info for the value of these caps. I would guess 8-12 are 100nf, but not sure on the others. edit...and T3 :)

Thanks

**Comment by gerb-ster** [comment]
Yes, you are right, those values where missing. I've updated the schematics! Your guesses were right; T3 should be a BC550C. They are noted in the schematics.
